### PR TITLE
chore: updated fastlane metadata

### PR DESCRIPTION
**Pull request by sjoerdlmkns**
This is needed for the F-Droid listing

Updated according to: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

### CODE REVIEW

**Comment by ivard** [comment]
Looks good. I noticed that we previously named the images `1.png`, `2.png`, etc. and now we have human readable names. Do you know whether that has impact on the order in which the images will be displayed?

**Comment by sjoerdlmkns** [comment]
The docs don't really specify this. I'll update it just to be sure.

**Comment by sjoerdlmkns** [comment]
Note: Apparently we only have 4 screenshots for Android and 5 for iOS

**Review by ivard — APPROVED** [review]

**Review by sanderhollaar — APPROVED** [review]

**Comment by ivard** [comment]
> Note: Apparently we only have 4 screenshots for Android and 5 for iOS

Apparently, we chose to add the ArrowBackScreen as screenshot so it makes sense that that one doesn't exist on Android.

**Pull request merged**
